import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HomeSection from "../components/homeSection/homeSection";
import RecentlyPlayed from "../components/recentlyPlayed/recentlyPlayed";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="bg-white dark:bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" pl-[13.5%] w-[98vw] min-h-[92.5vh] space-y-8 pb-40">
        <p className="text-3xl capitalize">good afternoon</p>
        <RecentlyPlayed />
        <HomeSection heading="Top rated" />
        <HomeSection heading="Recently played" />
        <HomeSection heading="Jump back in" />
        <HomeSection heading="Jump back in" />
        <HomeSection heading="Jump back in" />
        <HomeSection heading="Jump back in" />
        <HomeSection heading="Jump back in" />
        <HomeSection heading="Jump back in" />
      </main>
    </div>
  );
};

export default Home;
