import type { NextPage } from "next";
import Head from "next/head";

const Playlist: NextPage = () => {
  return (
    <div className="bg-white dark:bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" pl-[13.5%] w-[90vw] min-h-screen">
        <p>Playlist</p>
      </main>
    </div>
  );
};

export default Playlist;
